title: "[Announcement]: "
labels: ["announcement"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template for official VSCode+ announcements, releases, and major updates.
        
  - type: textarea
    attributes:
      label: "Announcement"
      description: "What would you like to announce?"
    validations:
      required: true
